### ISSUE TITLE
WikiFont Avatar icon is misaligned on Refreshed header

### ISSUE THREAD

**Issue by neoncitylights** [Coasterpedia/coasterpedia#2]
Since the header's height was customized and grew with custom CSS, the WikiFont avatar icon is misaligned. This can be changed by adjusting the line-height property:

``` css
.avatar-no-socialprofile.wikiglyph-user-sleep,
.avatar-no-socialprofile.wikiglyph-user-smile,
.wikiglyph-magnifying-glass {
line-height: 2em;
}
```

(Although personally, I like the custom header height and maybe with a commit it could actually be the default height for Refreshed, but I'd have to create a new task on Phabricator) 

Since it's not actually in the Refreshed core, this would have to be put in MediaWiki:Refreshed.css but maybe it can be put into core, if a discussion goes through and a consensus is reached. ^_^
