### ISSUE TITLE
Logo disappears on hover on Refreshed header

### ISSUE THREAD

**Issue by neoncitylights** [Coasterpedia/coasterpedia#3]
When the wiki logo is hovered over, it disappears! After some observation, it's a bit simple:

The circle logo is defined here:

``` css
#header-wrapper {
    background: #60AE26 url(http://coasterpedia.net/w/images/8/82/Corkcrew_circle.png);
    background-size: contain;
    background-repeat: no-repeat;
}
```

The hover is right here:

``` css
.header-button:hover, 
.header-dropdown-item:hover, 
.header-button-active, 
.sitedropdown-highlighted, 
.dropdown-highlighted {
    background-color: #69be2a;
    color: #fff;
}
```

What this does is overlay this left side of the #header-wrapper with just a completely flat background-color, so the background-image is hidden under. This can be fixed with:

``` css
.header-button:hover, 
.header-dropdown-item:hover,
.header-button-active,
.sitedropdown-highlighted, 
.dropdown-highlighted {
    background-color: #69be2a;
    background-image: url(http://coasterpedia.net/w/images/8/82/Corkcrew_circle.png);
    background-size: contain;
    background-repeat: no-repeat;
    color: #fff;
}
```
## However!

This is not the optimal solution :( :-1: First off, the circle logo should be combined with the wordmark text logo itself (located at http://coasterpedia.net/w/images/a/a8/Coasterpedia_logo_sladflskjdf.png ), and you can create a new file to upload this version of the logo and replace it. This is rather a simple fix by creating multiple layers in a photo editing the program (e.g Gimp or Inkscape), with the circle as the first layer and the text is the second layer (so it's on top), and then export it as a .png. I would be more than happy to do this when I get the time, if you'd like :smiley:
